language: node_js
node_js:
  - "9"
sudo: true
dist: trusty

branches:
  only:
  - master

script:
  - ng build --output-path dist --prod --base-href https://hexpy.github.io/PenPaperHero/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
